// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adv.proto

package adv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestStat struct {
	Sum                  int32    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStat) Reset()         { *m = RequestStat{} }
func (m *RequestStat) String() string { return proto.CompactTextString(m) }
func (*RequestStat) ProtoMessage()    {}
func (*RequestStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b150765472025a7e, []int{0}
}
func (m *RequestStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStat.Unmarshal(m, b)
}
func (m *RequestStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStat.Marshal(b, m, deterministic)
}
func (m *RequestStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStat.Merge(m, src)
}
func (m *RequestStat) XXX_Size() int {
	return xxx_messageInfo_RequestStat.Size(m)
}
func (m *RequestStat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStat proto.InternalMessageInfo

func (m *RequestStat) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *RequestStat) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AdvData struct {
	ReleaseTime          int64    `protobuf:"varint,1,opt,name=releaseTime,proto3" json:"releaseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvData) Reset()         { *m = AdvData{} }
func (m *AdvData) String() string { return proto.CompactTextString(m) }
func (*AdvData) ProtoMessage()    {}
func (*AdvData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b150765472025a7e, []int{1}
}
func (m *AdvData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvData.Unmarshal(m, b)
}
func (m *AdvData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvData.Marshal(b, m, deterministic)
}
func (m *AdvData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvData.Merge(m, src)
}
func (m *AdvData) XXX_Size() int {
	return xxx_messageInfo_AdvData.Size(m)
}
func (m *AdvData) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvData.DiscardUnknown(m)
}

var xxx_messageInfo_AdvData proto.InternalMessageInfo

func (m *AdvData) GetReleaseTime() int64 {
	if m != nil {
		return m.ReleaseTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestStat)(nil), "adv.RequestStat")
	proto.RegisterType((*AdvData)(nil), "adv.AdvData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdvServiceClient is the client API for AdvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdvServiceClient interface {
	Update(ctx context.Context, in *RequestStat, opts ...grpc.CallOption) (*AdvData, error)
}

type advServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdvServiceClient(cc *grpc.ClientConn) AdvServiceClient {
	return &advServiceClient{cc}
}

func (c *advServiceClient) Update(ctx context.Context, in *RequestStat, opts ...grpc.CallOption) (*AdvData, error) {
	out := new(AdvData)
	err := c.cc.Invoke(ctx, "/adv.AdvService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvServiceServer is the server API for AdvService service.
type AdvServiceServer interface {
	Update(context.Context, *RequestStat) (*AdvData, error)
}

func RegisterAdvServiceServer(s *grpc.Server, srv AdvServiceServer) {
	s.RegisterService(&_AdvService_serviceDesc, srv)
}

func _AdvService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adv.AdvService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvServiceServer).Update(ctx, req.(*RequestStat))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adv.AdvService",
	HandlerType: (*AdvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _AdvService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adv.proto",
}

func init() { proto.RegisterFile("adv.proto", fileDescriptor_b150765472025a7e) }

var fileDescriptor_b150765472025a7e = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4c, 0x29, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x4c, 0x29, 0x53, 0x32, 0xe5, 0xe2, 0x0e, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x2e, 0x49, 0x2c, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0x2e, 0xcd,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0x93, 0xf3, 0x4b,
	0xf3, 0x4a, 0x24, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x92, 0x36, 0x17, 0xbb, 0x63, 0x4a, 0x99, 0x4b,
	0x62, 0x49, 0xa2, 0x90, 0x02, 0x17, 0x77, 0x51, 0x6a, 0x4e, 0x6a, 0x62, 0x71, 0x6a, 0x48, 0x66,
	0x6e, 0x2a, 0x58, 0x2b, 0x73, 0x10, 0xb2, 0x90, 0x91, 0x05, 0x17, 0x97, 0x63, 0x4a, 0x59, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x16, 0x17, 0x5b, 0x68, 0x41, 0x4a, 0x62, 0x49, 0xaa,
	0x90, 0x80, 0x1e, 0xc8, 0x31, 0x48, 0xd6, 0x4b, 0xf1, 0x80, 0x45, 0xa0, 0x26, 0x2b, 0x31, 0x24,
	0xb1, 0x81, 0x5d, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xfb, 0xb7, 0x8b, 0xb6, 0x00,
	0x00, 0x00,
}
