apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: worker
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mockserver
    http:
      paths:
      - backend:
          serviceName: worker
          servicePort: 8080
          