// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idp.proto

package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QID) Reset()         { *m = QID{} }
func (m *QID) String() string { return proto.CompactTextString(m) }
func (*QID) ProtoMessage()    {}
func (*QID) Descriptor() ([]byte, []int) {
	return fileDescriptor_3020e615a04b7792, []int{0}
}
func (m *QID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QID.Unmarshal(m, b)
}
func (m *QID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QID.Marshal(b, m, deterministic)
}
func (m *QID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QID.Merge(m, src)
}
func (m *QID) XXX_Size() int {
	return xxx_messageInfo_QID.Size(m)
}
func (m *QID) XXX_DiscardUnknown() {
	xxx_messageInfo_QID.DiscardUnknown(m)
}

var xxx_messageInfo_QID proto.InternalMessageInfo

func (m *QID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Req struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_3020e615a04b7792, []int{1}
}
func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*QID)(nil), "go.micro.srv.consignment.QID")
	proto.RegisterType((*Req)(nil), "go.micro.srv.consignment.Req")
}

func init() { proto.RegisterFile("idp.proto", fileDescriptor_3020e615a04b7792) }

var fileDescriptor_3020e615a04b7792 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4c, 0x29, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7,
	0x2b, 0x2e, 0x2a, 0xd3, 0x4b, 0xce, 0xcf, 0x2b, 0xce, 0x4c, 0xcf, 0xcb, 0x4d, 0xcd, 0x2b, 0x51,
	0x12, 0xe5, 0x62, 0x0e, 0xf4, 0x74, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x01, 0x09, 0x07, 0xa5, 0x16, 0xa2, 0x0b, 0x1b, 0xf9, 0x70,
	0x31, 0x67, 0xa6, 0x14, 0x08, 0xb9, 0x72, 0x31, 0xfb, 0xa5, 0x96, 0x0b, 0xc9, 0xea, 0xe1, 0x32,
	0x56, 0x2f, 0x28, 0xb5, 0x50, 0x0a, 0x8f, 0x74, 0xa0, 0xa7, 0x8b, 0x12, 0x43, 0x12, 0x1b, 0xd8,
	0x71, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe8, 0x0c, 0x15, 0xa9, 0x00, 0x00, 0x00,
}
