apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
data:
 config.yml: |
    hostdb:
      'mockserver:80': mock
      'www.apichart.me:80': apichart
      'apichart.me:80': apichart
    targetdb:
      mock: 'mockserver:8888'
      apichart: '216.58.203.83:80'
  